/**
 * MicropolisMessage lists every possible message generated by the game engine.
 * Ports MicropolisMessage.java.
 */
export const MicropolisMessage = Object.freeze({
    // Demand and Infrastructure Messages
    NEED_RES: 'NEED_RES',
    NEED_COM: 'NEED_COM',
    NEED_IND: 'NEED_IND',
    NEED_ROADS: 'NEED_ROADS',
    NEED_RAILS: 'NEED_RAILS',
    NEED_POWER: 'NEED_POWER',
    NEED_STADIUM: 'NEED_STADIUM',
    NEED_SEAPORT: 'NEED_SEAPORT',
    NEED_AIRPORT: 'NEED_AIRPORT',
    
    // Quality of Life Alerts
    HIGH_POLLUTION: 'HIGH_POLLUTION',
    HIGH_CRIME: 'HIGH_CRIME',
    HIGH_TRAFFIC: 'HIGH_TRAFFIC',
    NEED_FIRESTATION: 'NEED_FIRESTATION',
    NEED_POLICE: 'NEED_POLICE',
    BLACKOUTS: 'BLACKOUTS',
    HIGH_TAXES: 'HIGH_TAXES',
    
    // Funding Alerts
    ROADS_NEED_FUNDING: 'ROADS_NEED_FUNDING',
    FIRE_NEED_FUNDING: 'FIRE_NEED_FUNDING',
    POLICE_NEED_FUNDING: 'POLICE_NEED_FUNDING',
    
    // Disaster Dispatches
    FIRE_REPORT: 'FIRE_REPORT',
    MONSTER_REPORT: 'MONSTER_REPORT',
    TORNADO_REPORT: 'TORNADO_REPORT',
    EARTHQUAKE_REPORT: 'EARTHQUAKE_REPORT',
    PLANECRASH_REPORT: 'PLANECRASH_REPORT',
    SHIPWRECK_REPORT: 'SHIPWRECK_REPORT',
    TRAIN_CRASH_REPORT: 'TRAIN_CRASH_REPORT',
    COPTER_CRASH_REPORT: 'COPTER_CRASH_REPORT',
    
    // Economic Operations
    HIGH_UNEMPLOYMENT: 'HIGH_UNEMPLOYMENT',
    OUT_OF_FUNDS_REPORT: 'OUT_OF_FUNDS_REPORT',
    FIREBOMBING_REPORT: 'FIREBOMBING_REPORT',
    NEED_PARKS: 'NEED_PARKS',
    EXPLOSION_REPORT: 'EXPLOSION_REPORT',
    INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
    BULLDOZE_FIRST: 'BULLDOZE_FIRST',
    
    // Population Milestones
    POP_2K_REACHED: 'POP_2K_REACHED',
    POP_10K_REACHED: 'POP_10K_REACHED',
    POP_50K_REACHED: 'POP_50K_REACHED',
    POP_100K_REACHED: 'POP_100K_REACHED',
    POP_500K_REACHED: 'POP_500K_REACHED',
    
    // Additional Hazards
    BROWNOUTS_REPORT: 'BROWNOUTS_REPORT',
    HEAVY_TRAFFIC_REPORT: 'HEAVY_TRAFFIC_REPORT',
    FLOOD_REPORT: 'FLOOD_REPORT',
    MELTDOWN_REPORT: 'MELTDOWN_REPORT',
    RIOTING_REPORT: 'RIOTING_REPORT',
    NO_NUCLEAR_PLANTS: 'NO_NUCLEAR_PLANTS'
});

// Private set tracking items flagged for persistent visual priority panels
const notificationPaneSet = new Set([
    MicropolisMessage.POP_2K_REACHED,
    MicropolisMessage.POP_10K_REACHED,
    MicropolisMessage.POP_50K_REACHED,
    MicropolisMessage.POP_100K_REACHED,
    MicropolisMessage.POP_500K_REACHED,
    MicropolisMessage.HIGH_CRIME,
    MicropolisMessage.HIGH_POLLUTION,
    MicropolisMessage.FLOOD_REPORT,
    MicropolisMessage.FIRE_REPORT,
    MicropolisMessage.TORNADO_REPORT,
    MicropolisMessage.MELTDOWN_REPORT,
    MicropolisMessage.EARTHQUAKE_REPORT,
    MicropolisMessage.TRAIN_CRASH_REPORT,
    MicropolisMessage.SHIPWRECK_REPORT,
    MicropolisMessage.COPTER_CRASH_REPORT,
    MicropolisMessage.PLANECRASH_REPORT
]);

/**
 * Determines whether a specific message key should occupy a sticky 
 * presence on the persistent notification pane. Ports useNotificationPane.
 * @param {string} messageKey - The MicropolisMessage string key to evaluate
 * @returns {boolean} True if the message requires persistent notification
 */
export function useNotificationPane(messageKey) {
    return notificationPaneSet.has(messageKey);
}