/**
 * Contains structural metric properties generated by the city map query tool.
 * Integer values correspond to index lookups parsed by the UI layer.
 * Ports ZoneStatus.java.
 */
export class ZoneStatus {
    constructor() {
        /** * Structural identification type index.
         * @type {number} 
         */
        this.building = 0;

        /** * Density representation metric.
         * @type {number} 
         */
        this.popDensity = 0;

        /** * Economic land value tier index.
         * @type {number} 
         */
        this.landValue = 0;

        /** * Crime concentration index.
         * @type {number} 
         */
        this.crimeLevel = 0;

        /** * Environmental pollution density level.
         * @type {number} 
         */
        this.pollution = 0;

        /** * Neighborhood economic growth rate momentum.
         * @type {number} 
         */
        this.growthRate = 0;
    }
}